name: Update Heartbeat
on:
  workflow_dispatch:
jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Commit and deploy
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        LAST_MSG=$(git log -1 --pretty=%s)
        if [ "$LAST_MSG" = "update heartbeat" ]; then
          git reset --soft HEAD~1
        fi
        echo "{\"date\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > heartbeat.json
        git add heartbeat.json
        git commit -m "update heartbeat"
        git push --force-with-lease
